#!/bin/sh
cat protocol/DNP3Controller.js \
	spacer.js \
	protocol/ENIPIOController.js \
	spacer.js \
	protocol/ENIPTCPController.js \
	spacer.js \
	protocol/ENIPUDPController.js \
	spacer.js \
	protocol/FTPController.js \
	spacer.js \
	protocol/GOOSEController.js \
	spacer.js \
	protocol/HTTPController.js \
	spacer.js \
	protocol/IEC104Controller.js \
	spacer.js \
	protocol/MMSController.js \
	spacer.js \
	protocol/MODBUSController.js \
	spacer.js \
	protocol/OPCDAController.js \
	spacer.js \
	protocol/OPCUAController.js \
	spacer.js \
	protocol/PNRTDCPController.js \
	spacer.js \
	protocol/POP3Controller.js \
	spacer.js \
	protocol/PROFINETIOController.js \
	spacer.js \
	protocol/S7Controller.js \
	spacer.js \
	protocol/SMTPController.js \
	spacer.js \
	protocol/SNMPController.js \
	spacer.js \
	protocol/SVController.js \
	spacer.js \
	protocol/TELNETController.js \
	> protocol.js
